// Core configuration
export const CONFIG = {
  defaults: {
    clockFormat: "12",
    clockType: "digital",
    tempUnit: "metric",
    widgetControl: "all",
    showTodo: true,
    showApps: true,
    shortcutsPosition: "bottom",
    shortcutsDisplayMode: "shortcuts",
    fontFamily: "outfit",
    newsEnabled: false,
    newsPermissionModelVersion: 0,
    newsBadgeDismissed: false,
    newsProviderIds: ["bbc", "guardian", "cnn"],
    newsCategoryIds: ["top", "world"],
    newsShowHeadlines: true,
    newsHeadlineOpacity: 50,
    newsTotalCards: 6,
    newsRefreshIntervalMinutes: 2,
    newsPosition: "bottom",
    newsConsentRemembered: false,
    newsCache: {
      version: 2,
      imageParserVersion: 6,
      ageMinutes: 0,
      selectionKey: "",
      lastAttemptAt: 0,
      fetchedAt: 0,
      items: [],
      failures: [],
    },
    showAiTools: true,
    showEditableText: true,
    disableAnimations: false,
    disableAnimationsToggleCount: 0,
    glowEffect: false,
    glowDefaultOffMigrated: false,
    glassmorphismUseCount: 0,
    fontFamilyUseCount: 0,
    randomBgSchedule: "1m",
    randomBgScheduleBadgeDismissed: false,
    randomBgRefreshWarningDismissed: false,
    randomBgLastChangedAt: 0,
    randomBgLastChangedDate: "",
    randomBgCurrentPreview: "",
    settingsShortcutUseCount: 0,
    miniSettingsShortcutUseCount: 0,
    darkModeToggleUseCount: 0,
    weatherLocationSaveCount: 0,
    lavenderMistThemeUseCount: 0,
    dawnBloomThemeUseCount: 0,
    mistralToolUseCount: 0,
    tiktokToolUseCount: 0,
    perplexityUseCount: 0,
    themeGeneratorUseCount: 0,
    todos: [
      {
        id: "dt-1",
        text: "Checkout the Setting for Functions & Customization",
        completed: false,
        pinned: false,
      },
      {
        id: "dt-2",
        text: "Click INFO button in the corner of Settings",
        completed: false,
        pinned: false,
      },
      {
        id: "dt-3",
        text: "Double-Click the Greeting text to set your Name",
        completed: false,
        pinned: false,
      },
      {
        id: "dt-4",
        text: "Click the Google icon in Search Box to change it",
        completed: false,
        pinned: false,
      },
      {
        id: "dt-5",
        text: "Go to Settings > Appearance & select a Theme",
        completed: false,
        pinned: false,
      },
    ],
    welcomeText: "Click to edit",
    searchProvider: { id: "google", type: "engines" },
    googleAiSearchActive: false,
    googleAiSearchUsed: false,
    googleAiSearchHintShownCount: 0,
    searchSuggestionMode: "history-only",
    searchSuggestionProxyUrl: "",
    searchSuggestionConsentRemembered: false,
    searchSuggestionBadgeDismissed: false,
    customSearchEngines: [],
    customAiTools: [],
    customSocialLinks: [],
    customApps: [],
    googleAppOverrides: {},
    hiddenApps: {},
    appsEditHintCount: 0,
    gradientColorThemeId: "",
    gradientColor1: "",
    gradientColor2: "",
    hiddenTools: {},
    hiddenToolsDefaultsMigrated: false,
    autoTheme: false,
    zenMode: false,
    zenNoticeAcknowledged: false,
    miniSettingsHintShown: false,
    themeGenerationHintShown: false,
    miniSettingsOpenCount: 0,
    fullSettingsEverOpened: false,
    darkMode: true,
    darkSignalBackgroundActive: true,
    darkSignalBackgroundEverActivated: false,
    darkSignalBackgroundHintCount: 0,
    transparencyActive: true,
    grayscaleActive: true,
    normalThemeId: "default-dark",
    linkTargets: {
      ai: "_blank",
      apps: "_blank",
      shortcuts: "_blank",
      searchOpen: "_blank",
      news: "_blank",
    },
    searchHistory: [],
    searchHistoryPaused: false,
    searchAutoDeleteDays: 365,
    commandPaletteShortcutUseCount: 0,
    commandUsage: {},
  },
  paths: {
    icons: "assets/icons/",
    search: "assets/search-tools/",
    apps: "assets/google-apps/",
    ai: "assets/ai-tools/",
    social: "assets/socials/",
  },
};

// Font options
export const FONT_OPTIONS = Object.freeze([
  Object.freeze({
    id: "lexend",
    label: "Lexend",
    googleFamily: "Lexend:wght@400;500;700",
    stack: '"Lexend", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "inter",
    label: "Inter",
    googleFamily: "Inter:wght@400;600;700;800",
    stack: '"Inter", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "roboto",
    label: "Roboto",
    googleFamily: "Roboto:wght@400;500;700",
    stack: '"Roboto", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "manrope",
    label: "Manrope",
    googleFamily: "Manrope:wght@400;500;600;700",
    stack: '"Manrope", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "outfit",
    label: "Outfit",
    googleFamily: "Outfit:wght@400;500;600;700",
    stack: '"Outfit", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "nunito",
    label: "Nunito",
    googleFamily: "Nunito:wght@400;500;600;700",
    stack: '"Nunito", system-ui, sans-serif',
  }),
  Object.freeze({
    id: "merriweather",
    label: "Merriweather",
    googleFamily: "Merriweather:wght@400;700",
    stack: '"Merriweather", Georgia, serif',
  }),
  Object.freeze({
    id: "roboto-mono",
    label: "Roboto Mono",
    googleFamily: "Roboto Mono:wght@400;500;700",
    stack: '"Roboto Mono", ui-monospace, monospace',
  }),
]);

// News configuration
export const NEWS_REFRESH_INTERVALS = Object.freeze([1, 2, 5, 10]);
export const NEWS_HEADLINE_OPACITIES = Object.freeze([0, 30, 50, 70]);
export const NEWS_CARD_COUNTS = Object.freeze([4, 5, 6, 7]);
export const NEWS_MIN_REFETCH_MS = 60 * 1000;

export const NEWS_CATEGORIES = Object.freeze([
  { id: "top", label: "Top stories" },
  { id: "world", label: "World" },
  { id: "politics", label: "Politics" },
  { id: "business", label: "Business" },
  { id: "technology", label: "Technology" },
  { id: "science", label: "Science" },
  { id: "health", label: "Health" },
  { id: "sports", label: "Sports" },
  { id: "entertainment", label: "Culture" },
  { id: "environment", label: "Environment" },
  { id: "finance", label: "Finance" },
  { id: "education", label: "Education" },
  { id: "travel", label: "Travel" },
  { id: "lifestyle", label: "Lifestyle" },
  { id: "opinion", label: "Opinion" },
  { id: "crime", label: "Crime" },
]);

export const NEWS_PROVIDERS = Object.freeze([
  {
    id: "bbc",
    name: "BBC News",
    shortName: "BBC",
    color: "#bb1919",
    permission: "https://feeds.bbci.co.uk/*",
    feeds: {
      top: "https://feeds.bbci.co.uk/news/rss.xml",
      world: "https://feeds.bbci.co.uk/news/world/rss.xml",
      politics: "https://feeds.bbci.co.uk/news/politics/rss.xml",
      business: "https://feeds.bbci.co.uk/news/business/rss.xml",
      technology: "https://feeds.bbci.co.uk/news/technology/rss.xml",
      science: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml",
      health: "https://feeds.bbci.co.uk/news/health/rss.xml",
      sports: "https://feeds.bbci.co.uk/sport/rss.xml",
      entertainment:
        "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    },
  },
  {
    id: "guardian",
    name: "The Guardian",
    shortName: "G",
    color: "#052962",
    permission: "https://www.theguardian.com/*",
    feeds: {
      top: "https://www.theguardian.com/international/rss",
      world: "https://www.theguardian.com/world/rss",
      politics: "https://www.theguardian.com/politics/rss",
      business: "https://www.theguardian.com/business/rss",
      technology: "https://www.theguardian.com/technology/rss",
      science: "https://www.theguardian.com/science/rss",
      health: "https://www.theguardian.com/society/health/rss",
      sports: "https://www.theguardian.com/sport/rss",
      entertainment: "https://www.theguardian.com/culture/rss",
      environment: "https://www.theguardian.com/environment/rss",
      finance: "https://www.theguardian.com/money/rss",
      education: "https://www.theguardian.com/education/rss",
      travel: "https://www.theguardian.com/travel/rss",
      lifestyle: "https://www.theguardian.com/lifeandstyle/rss",
      opinion: "https://www.theguardian.com/commentisfree/rss",
      crime: "https://www.theguardian.com/uk-news/crime/rss",
    },
  },
  {
    id: "cnn",
    name: "CNN",
    shortName: "CNN",
    color: "#cc0000",
    format: "cnn-search-json",
    permission: "https://search.prod.di.api.cnn.io/*",
    feeds: {
      top: "https://search.prod.di.api.cnn.io/content?category=top",
      world: "https://search.prod.di.api.cnn.io/content?category=world",
      politics: "https://search.prod.di.api.cnn.io/content?category=politics",
      business: "https://search.prod.di.api.cnn.io/content?category=business",
      technology:
        "https://search.prod.di.api.cnn.io/content?category=technology",
      science: "https://search.prod.di.api.cnn.io/content?category=science",
      health: "https://search.prod.di.api.cnn.io/content?category=health",
      sports: "https://search.prod.di.api.cnn.io/content?category=sports",
      entertainment:
        "https://search.prod.di.api.cnn.io/content?category=entertainment",
      travel: "https://search.prod.di.api.cnn.io/content?category=travel",
    },
  },
  {
    id: "npr",
    name: "NPR",
    shortName: "NPR",
    color: "#d62021",
    permission: "https://feeds.npr.org/*",
    feeds: {
      top: "https://feeds.npr.org/1001/rss.xml",
      world: "https://feeds.npr.org/1001/rss.xml",
    },
  },
  {
    id: "dw",
    name: "DW",
    shortName: "DW",
    color: "#0087c9",
    permission: "https://rss.dw.com/*",
    feeds: {
      top: "https://rss.dw.com/rdf/rss-en-all",
      world: "https://rss.dw.com/rdf/rss-en-all",
    },
  },
  {
    id: "euronews",
    name: "Euronews",
    shortName: "EU",
    color: "#003399",
    permission: "https://www.euronews.com/*",
    feeds: {
      top: "https://www.euronews.com/rss?level=theme&name=news",
      world: "https://www.euronews.com/rss?level=theme&name=news",
      business: "https://www.euronews.com/rss?level=theme&name=business",
      technology: "https://www.euronews.com/rss?level=theme&name=next",
      sports: "https://www.euronews.com/rss?level=theme&name=sport",
      entertainment: "https://www.euronews.com/rss?level=theme&name=culture",
      environment: "https://www.euronews.com/rss?level=theme&name=green",
    },
  },
]);

export const COMMAND_PALETTE_SHORTCUT_USE_LIMIT = 3;

// Quote content
export const QUOTES = [
  {
    text: "The only way to do great work is to love what you do.",
    author: "Steve Jobs",
  },
  {
    text: "Code is like humor. When you have to explain it, it’s bad.",
    author: "Cory House",
  },
  { text: "Simplicity is the soul of efficiency.", author: "Austin Freeman" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  {
    text: "First, solve the problem. Then, write the code.",
    author: "John Johnson",
  },
  {
    text: "We suffer more often in imagination than in reality.",
    author: "Seneca",
  },
  { text: "Discipline equals freedom.", author: "Jocko Willink" },
  { text: "The obstacle is the way.", author: "Ryan Holiday" },
  {
    text: "You have the right to work, but never to the fruit of work.",
    author: "Shree Krishna",
  },
  { text: "Change is the law of the universe.", author: "Shree Krishna" },
  {
    text: "Man is made by his belief. As he believes, so he is.",
    author: "Shree Krishna",
  },
  {
    text: "Nature does not hurry, yet everything is accomplished.",
    author: "Lao Tzu",
  },
  {
    text: "Arise, awake, and stop not till the goal is reached.",
    author: "Swami Vivekananda",
  },
  { text: "Your ego is your soul's worst enemy.", author: "Rusty Eric" },
  {
    text: "If you are going through hell, keep going.",
    author: "Winston Churchill",
  },
  { text: "Happiness depends upon ourselves.", author: "Aristotle" },
  { text: "Knowledge is power.", author: "Francis Bacon" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "I think, therefore I am.", author: "René Descartes" },
  { text: "Knowledge is power.", author: "Sir Francis Bacon" },
  {
    text: "To be, or not to be, that is the question.",
    author: "William Shakespeare",
  },
  { text: "I came, I saw, I conquered.", author: "Julius Caesar" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
  { text: "Be loyal to what matters.", author: "Arthur Morgan" },
  {
    text: "We can't change what's done, we can only move on.",
    author: "Arthur Morgan",
  },
  { text: "Do or do not. There is no try.", author: "Yoda" },
  {
    text: "Simplicity is the ultimate sophistication.",
    author: "Leonardo da Vinci",
  },
  { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
  {
    text: "He who has a why to live can bear almost any how.",
    author: "Friedrich Nietzsche",
  },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "No pressure, no diamonds.", author: "Thomas Carlyle" },
  { text: "Leave no stone unturned.", author: "Euripides" },
  {
    text: "Have no fear of perfection, you'll never reach it.",
    author: "Marie Curie",
  },
  { text: "Make each day your masterpiece.", author: "John Wooden" },
  { text: "Be water, my friend.", author: "Bruce Lee" },
  {
    text: "The only real mistake is the one we learn nothing from.",
    author: "Henry Ford",
  },
  {
    text: "Action is the foundational key to all success.",
    author: "Pablo Picasso",
  },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  {
    text: "Tough times never last, but tough people do.",
    author: "Robert H. Schuller",
  },
  {
    text: "It always seems impossible until it's done.",
    author: "Nelson Mandela",
  },
  { text: "Well begun is half done.", author: "Aristotle" },
  {
    text: "The future depends on what you do today.",
    author: "Mahatma Gandhi",
  },
  {
    text: "What you do speaks so loudly that I cannot hear what you say.",
    author: "Ralph Waldo Emerson",
  },
  {
    text: "Great things are done by a series of small things brought together.",
    author: "Vincent van Gogh",
  },
  {
    text: "Success is the sum of small efforts, repeated day in and day out.",
    author: "Robert Collier",
  },
  {
    text: "The secret of getting ahead is getting started.",
    author: "Mark Twain",
  },
  {
    text: "In the middle of difficulty lies opportunity.",
    author: "Albert Einstein",
  },
  {
    text: "The journey of a thousand miles begins with one step.",
    author: "Lao Tzu",
  },
  {
    text: "It does not matter how slowly you go as long as you do not stop.",
    author: "Confucius",
  },
  {
    text: "A person who never made a mistake never tried anything new.",
    author: "Albert Einstein",
  },
  { text: "The best way out is always through.", author: "Robert Frost" },
  {
    text: "Believe you can and you're halfway there.",
    author: "Theodore Roosevelt",
  },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  {
    text:
      "The future belongs to those who believe in the beauty of their dreams.",
    author: "Eleanor Roosevelt",
  },
  {
    text: "Start where you are. Use what you have. Do what you can.",
    author: "Arthur Ashe",
  },
  {
    text: "If opportunity doesn't knock, build a door.",
    author: "Milton Berle",
  },
  {
    text: "Don't count the days, make the days count.",
    author: "Muhammad Ali",
  },
  {
    text: "You miss 100% of the shots you don't take.",
    author: "Wayne Gretzky",
  },
  {
    text:
      "The only limit to our realization of tomorrow is our doubts of today.",
    author: "Franklin D. Roosevelt",
  },
];

// Google app definitions
export const GOOGLE_APPS = [
  {
    name: "Account",
    url: "https://myaccount.google.com/",
    icon: "account.png",
  },
  { name: "Google", url: "https://www.google.com/", icon: "google.png" },
  { name: "YouTube", url: "https://www.youtube.com/", icon: "yt.png" },
  { name: "Gmail", url: "https://mail.google.com/", icon: "gmail.png" },
  {
    name: "YT Music",
    url: "https://music.youtube.com/",
    icon: "ytmusic.png",
    height: "45px",
    width: "45px",
  },
  {
    name: "Maps",
    url: "https://maps.google.com/",
    icon: "maps.png",
    height: "43px",
    width: "43px",
  },
  {
    name: "Play",
    url: "https://play.google.com/",
    icon: "play.png",
    height: "50px",
    width: "50px",
  },
  { name: "Drive", url: "https://drive.google.com/", icon: "drive.png" },
  { name: "Photos", url: "https://photos.google.com/", icon: "photos.png" },
  {
    name: "Translate",
    url: "https://translate.google.com/",
    icon: "translate.png",
  },
  {
    name: "Calendar",
    url: "https://calendar.google.com/",
    icon: "calendar.png",
  },
  {
    name: "Meet",
    url: "https://meet.google.com/",
    icon: "meet.png",
    height: "40px",
    width: "40px",
  },
  { name: "divider" },
  { name: "Docs", url: "https://docs.google.com/", icon: "docs.png" },
  { name: "Sheets", url: "https://sheets.google.com/", icon: "sheets.png" },
  { name: "Slides", url: "https://slides.google.com/", icon: "slides.png" },
  {
    name: "Chat",
    url: "https://chat.google.com/",
    icon: "chat.png",
    height: "45px",
    width: "45px",
  },
  { name: "Books", url: "https://books.google.com/", icon: "books.png" },
  { name: "News", url: "https://news.google.com/", icon: "news.png" },
  { name: "Forms", url: "https://forms.google.com/", icon: "forms.png" },
  {
    name: "Contacts",
    url: "https://contacts.google.com/",
    icon: "contact.png",
    height: "50px",
    width: "50px",
  },
  {
    name: "Travel",
    url: "https://www.google.com/travel/",
    icon: "travel.png",
  },
  { name: "Ads", url: "https://ads.google.com/", icon: "ads.png" },
  {
    name: "Business Profile",
    url: "https://business.google.com/",
    icon: "businessprofile.png",
  },
  {
    name: "Shopping",
    url: "https://shopping.google.com/",
    icon: "shopping.png",
  },
  {
    name: "Ad Center",
    url: "https://myadcenter.google.com/",
    icon: "adcenter.png",
  },
  { name: "Tasks", url: "https://tasks.google.com/", icon: "tasks.png" },
  { name: "Vids", url: "https://vids.google.com/", icon: "vids.png" },
  {
    name: "Google One",
    url: "https://one.google.com/",
    icon: "one.png",
    height: "45px",
    width: "45px",
  },
  { name: "Keep", url: "https://keep.google.com/", icon: "keep.png" },
  {
    name: "Passwords",
    url: "https://passwords.google.com/",
    icon: "password.png",
    height: "40px",
    width: "40px",
  },
  {
    name: "Classroom",
    url: "https://classroom.google.com/",
    icon: "classroom.png",
    height: "45px",
    width: "45px",
  },
  {
    name: "Blogger",
    url: "https://www.blogger.com/",
    icon: "blogger.png",
    height: "40px",
    width: "40px",
  },
  {
    name: "Earth",
    url: "https://earth.google.com/",
    icon: "earth.png",
    height: "40px",
    width: "40px",
  },
  {
    name: "WebStore",
    url: "https://chromewebstore.google.com/",
    icon: "store.png",
    height: "45px",
    width: "45px",
  },
  {
    name: "NotebookLM",
    url: "https://notebooklm.google.com/",
    icon: "notebooklm.png",
  },
  {
    name: "Wallet",
    url: "https://wallet.google/",
    icon: "wallet.png",
    height: "40px",
    width: "40px",
  },
];

// AI tool definitions
export const AI_TOOLS = [
  {
    name: "Claude",
    url: "https://claude.ai/new/",
    icon: "claude.png",
    id: "ai-claude",
  },
  {
    name: "Gemini",
    url: "https://gemini.google.com/",
    icon: "gemini.png",
    id: "ai-gemini",
  },
  {
    name: "ChatGPT",
    url: "https://chat.openai.com/",
    icon: "chatgpt.png",
    id: "ai-chatgpt",
  },
  {
    name: "Copilot",
    url: "https://copilot.microsoft.com/",
    icon: "copilot.png",
    id: "ai-copilot",
  },
  {
    name: "DeepSeek",
    url: "https://chat.deepseek.com/",
    icon: "deepseek.png",
    id: "ai-deepseek",
  },
  {
    name: "Qwen",
    url: "https://chat.qwen.ai/",
    icon: "qwen.png",
    id: "ai-qwen",
  },
  { name: "Grok", url: "https://grok.com/", icon: "grok.png", id: "ai-grok" },
  {
    name: "Meta AI",
    url: "https://www.meta.ai/",
    icon: "metaai.png",
    id: "ai-meta",
  },
  {
    name: "Perplexity",
    url: "https://www.perplexity.ai/",
    icon: "perplexity.png",
    id: "ai-perplexity",
  },
  {
    name: "Mistral",
    url: "https://chat.mistral.ai/",
    icon: "mistral.png",
    id: "ai-mistral",
  },
];

// Social link definitions
export const SOCIAL_LINKS = [
  {
    name: "Facebook",
    url: "https://www.facebook.com/",
    icon: "fb.png",
    id: "social-facebook",
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/",
    icon: "insta.png",
    id: "social-instagram",
  },
  {
    name: "X (Twitter)",
    url: "https://www.twitter.com/",
    icon: "x.png",
    id: "social-x",
  },
  {
    name: "WhatsApp",
    url: "https://web.whatsapp.com/",
    icon: "wa.png",
    id: "social-whatsapp",
  },
  {
    name: "Discord",
    url: "https://discord.com/app",
    icon: "dc.png",
    id: "social-discord",
  },
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/",
    icon: "ln.png",
    id: "social-linkedin",
  },
  {
    name: "Telegram",
    url: "https://web.telegram.org/",
    icon: "tg.png",
    id: "social-telegram",
  },
  {
    name: "Messenger",
    url: "https://www.messenger.com/",
    icon: "messenger.png",
    id: "social-messenger",
  },
  {
    name: "Snapchat",
    url: "https://web.snapchat.com/",
    icon: "sc.png",
    id: "social-snapchat",
  },
  {
    name: "TikTok",
    url: "https://www.tiktok.com/",
    icon: "tiktok.png",
    id: "social-tiktok",
  },
];

// Search provider definitions
export const SEARCH_PROVIDERS = {
  engines: [
    {
      id: "google",
      name: "Google",
      url: "https://www.google.com/search",
      queryParam: "q",
      icon: "google.png",
    },
    {
      id: "bing",
      name: "Bing",
      url: "https://www.bing.com/search",
      queryParam: "q",
      icon: "bing.png",
    },
    {
      id: "yahoo",
      name: "Yahoo",
      url: "https://search.yahoo.com/search",
      queryParam: "p",
      icon: "yahoo.png",
    },
    {
      id: "perplexity",
      name: "Perplexity",
      url: "https://www.perplexity.ai/search",
      queryParam: "q",
      icon: "assets/ai-tools/perplexity.png",
    },
    {
      id: "duckduckgo",
      name: "DuckDuckGo",
      url: "https://duckduckgo.com/",
      queryParam: "q",
      icon: "duckduckgo.png",
    },
    {
      id: "yandex",
      name: "Yandex",
      url: "https://yandex.com/search/",
      queryParam: "text",
      icon: "yandex.png",
    },
  ],
  platforms: [
    {
      id: "youtube",
      name: "YouTube",
      url: "https://www.youtube.com/results",
      queryParam: "search_query",
      icon: "youtube.png",
    },
    {
      id: "spotify",
      name: "Spotify",
      url: "https://open.spotify.com/search",
      queryParam: "",
      searchType: "path",
      icon: "spotify.png",
    },
    {
      id: "wikipedia",
      name: "Wikipedia",
      url: "https://en.wikipedia.org/w/index.php",
      queryParam: "search",
      icon: "wikipedia.png",
    },
    {
      id: "pinterest",
      name: "Pinterest",
      url: "https://www.pinterest.com/search/pins/",
      queryParam: "q",
      icon: "pinterest.png",
    },
    {
      id: "reddit",
      name: "Reddit",
      url: "https://www.reddit.com/search/",
      queryParam: "q",
      icon: "reddit.png",
    },
    {
      id: "quora",
      name: "Quora",
      url: "https://www.quora.com/search",
      queryParam: "q",
      icon: "quora.png",
    },
  ],
};

// Search suggestion definitions
export const SEARCH_SUGGESTIONS = [
  "How to learn a new language",
  "Easy dinner recipes for tonight",
  "Latest world news headlines",
  "Best movies of the year",
  "How to save money effectively",
  "Local weather forecast",
  "Online courses for coding",
  "Symptoms of the common cold",
  "Best places to travel in Europe",
  "How to write a professional resume",
  "DIY home decor ideas",
  "Beginner workout routines at home",
  "What is cryptocurrency?",
  "Healthy breakfast ideas",
  "Top 10 most popular songs",
  "How to tie a tie",
  "Latest smartphone reviews",
  "Gardening tips for beginners",
  "How to sleep better at night",
  "Stock market today",
  "Translate English to Spanish",
  "Learn to play guitar for beginners",
  "Best books to read this year",
  "How to start a small business",
  "Easy chicken recipes",
  "Meditation for anxiety",
  "Cheap flight tickets",
  "What is Artificial Intelligence?",
  "How to fix a leaky faucet",
  "Job search websites",
  "Best TV shows on Netflix",
  "How to cook rice perfectly",
  "Daily horoscope",
  "Funny cat videos",
  "Productivity tips for work",
  "How to create a website",
  "Healthy smoothie recipes",
  "Amazon online shopping",
  "Wikipedia",
  "YouTube",
  "Best coffee shops near me",
  "How to improve memory",
  "Latest fashion trends",
  "Car maintenance tips",
  "How to set personal goals",
  "Best cameras for photography",
  "Learn digital marketing",
  "Easy dessert recipes",
  "How to be more confident",
  "History of the internet",
  "Top AI tools for productivity",
  "Latest breakthroughs in fusion energy",
  "How to protect data privacy online",
  "Future of remote work trends",
  "Quantum computing explained simply",
  "Best coding languages for AI",
  "SpaceX Starship mission updates",
  "Impact of automation on the economy",
  "Sustainable living tips for beginners",
  "Advances in CRISPR gene editing",
  "How to build a personal knowledge base",
  "Electric vehicle battery tech news",
  "Ethical implications of AGI",
  "Digital nomad visa requirements",
  "Future of vertical farming",
  "Best open source LLMs to try",
  "Augmented Reality glasses reviews",
  "How to detect AI generated text",
  "Career skills for the AI era",
  "Renewable energy investment trends",
  "Psychology of social media addiction",
  "Latest James Webb Telescope images",
  "Neuralink and brain-computer interfaces",
  "Guide to self-hosting cloud services",
  "Biohacking tips for longevity",
  "How LLMs change software engineering",
  "ChatGPT",
  "WhatsApp Web",
  "Google Translate",
  "Gmail login",
  "Google Docs",
  "Google Calendar",
  "Google Flights",
  "Canva",
  "Instagram",
  "Discord",
  "LinkedIn",
  "Netflix",
  "What is my IP address",
  "What time is it",
  "What day is it today",
  "What is the weather today",
  "Weather tomorrow",
  "Google Maps",
  "Internet speed test",
  "Calculator",
  "Currency converter",
  "Unit converter",
  "Time zone converter",
  "Percentage calculator",
  "Mortgage calculator",
  "Loan calculator",
  "Compound interest calculator",
  "Bitcoin price",
  "Gold price",
  "What is an API",
  "What is a URL",
  "What is machine learning",
  "What is generative AI",
  "What is an LLM",
  "What is a VPN",
  "What is phishing",
  "What is blockchain",
  "What is cloud computing",
  "What is data privacy",
  "What is a password manager",
  "What is two factor authentication",
  "How to learn JavaScript",
  "How to learn Python",
  "Learn coding online",
  "Free online courses",
  "Online dictionary",
  "Grammar checker",
  "How to write a cover letter",
  "How to prepare for an interview",
  "How to start freelancing",
  "Resume template",
  "How to make a budget",
  "How to save money",
  "How to invest money",
  "How to build credit",
  "How to calculate percentages",
  "How to screenshot on Windows",
  "How to take a screenshot",
  "How to convert PDF to Word",
  "How to merge PDF files",
  "How to compress a PDF",
  "How to edit a PDF",
  "How to create a PDF",
  "How to clear browser cache",
  "How to clear cache on iPhone",
  "How to speed up a laptop",
  "How to free up storage",
  "How to back up your phone",
  "How to scan a QR code",
  "How to share WiFi password",
  "How to reset a router",
  "How to fix slow internet",
  "How to check battery health",
  "How to update apps",
  "How to turn on dark mode",
  "How to use Google Drive",
  "How to make a presentation",
  "How to zip a file",
  "How to learn faster",
  "How to improve focus",
  "How to build good habits",
  "How to reduce stress",
  "How to relax",
  "How to fall asleep fast",
  "How to improve posture",
  "How to lose weight",
  "How to gain weight",
  "How long to boil eggs",
  "How to cook pasta",
  "How to make coffee",
  "How to change a tire",
  "How to fix a running toilet",
  "How to remove a stain",
  "How to clean a microwave",
  "How to grow tomatoes",
  "How to care for houseplants",
  "Healthy meal ideas",
  "Home workout routine",
  "Jobs near me",
  "What to watch",
];

// Search suggestion modes
export const SEARCH_SUGGESTION_MODES = Object.freeze({
  HISTORY_ONLY: "history-only",
  HISTORY_ONLINE: "history-online",
  HISTORY_CUSTOM: "history-custom",
});

// Keyboard defaults
export const DEFAULT_KEY_MAP = {
  todo: { key: "t", enabled: true },
  ai: { key: "a", enabled: true },
  apps: { key: "g", enabled: true },
  settings: { key: "s", enabled: true },
  miniSettings: { key: "m", enabled: true },
  search: { key: "/", enabled: true },
  clock: { key: "c", enabled: false },
  date: { key: "d", enabled: false },
  autoTheme: { key: "e", enabled: false },
  tempDisplay: { key: "f", enabled: false },
  hideGreetings: { key: "j", enabled: false },
  showEditableText: { key: "k", enabled: false },
  numKeys: { key: "1-9", enabled: true, fixed: true },
  zen: { key: "z", enabled: true, fixed: true },
  voice: { key: "v", enabled: true, fixed: true },
};
// [src/config.js] YourDynamicDashboard V3.0.0 (Ditom Baroi Antu - 2025-26)
